name: CheckStyle

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  pull_request_target:
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:
  check-style:
    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')
    name: Check Style
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact: [ rabbit-hole, demo-app ]

    steps:

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Git Checkout
        uses: actions/checkout@v3
        # Do not trigger a checkout when opening PRs from a fork (helps avoid
        # "pwn request". See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target )
        if: github.event_name != 'pull_request_target'
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Dependabot Checkout
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request_target'
        with:
          # Dependabot can only do the checkout at the HEAD of the PR branch
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Gradle Style Check
        id: check-style
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew ${{ matrix.artifact }}:spotlessCheck
