name: Code Style

on: [pull_request]

jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Get Gradle Version
        id: gradle
        # In the `run` stage here we parse out the Gradle version from
        # `gradle-wrapper.properties` and pass it to the `output` of our
        # Job step:
        run: |
          properties="./gradle/wrapper/gradle-wrapper.properties"
          version="$(grep distributionUrl $properties | cut -d'-' -f2)"
          echo "::set-output name=version::$version"
      - name: Install Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Gradle Style Check
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          # Here we consume the `output` from our `Get Gradle Version` step:
          gradle-version: ${{ steps.gradle.version }}
          arguments: spotlessJavaCheck
          wrapper-cache-enabled: false
