name: Release

on:
  release:
    types: [published]

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact: [ rabbit-hole ]

    steps:

      - name: Install Java
        uses: actions/setup-java@v2.4.0
        with:
          java-version: 11
          distribution: 'adopt'

      - uses: actions/checkout@v2.4.0

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --tags | cut -d- -f 1)

      - name: Set Artifact Version
        run: |
          echo Artifact version: ${{ steps.get_version.outputs.VERSION }}
          echo "version=${{ steps.get_version.outputs.VERSION }}" > gradle.properties

      - name: Build Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew ${{ matrix.artifact }}:build

      - name: Publish Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew ${{ matrix.artifact }}:publish
