name: Release

on:
  release:
    types: [published]

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Get Gradle Version
        id: gradle
        # In the `run` stage here we parse out the Gradle version from
        # `gradle-wrapper.properties` and pass it to the `output` of our
        # Job step:
        run: |
          properties="./gradle/wrapper/gradle-wrapper.properties"
          version="$(grep distributionUrl $properties | cut -d'-' -f2)"
          echo "::set-output name=version::$version"
      - name: Get Release Tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1

      - name: Set Artifact Version
        run: |
          echo Artifact version: ${{ steps.previoustag.outputs.tag }}
          echo "version=${{ steps.previoustag.outputs.tag }}" > gradle.properties

      - name: Install Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build Artifact
        uses: eskatos/gradle-command-action@v1.5.1
        with:
          # Here we consume the `output` from our `Get Gradle Version` step:
          gradle-version: ${{ steps.gradle.version }}
          arguments: build
          wrapper-cache-enabled: false
          dependencies-cache-enabled: false
          configuration-cache-enabled: false

      - name: Publish Artifact
        uses: eskatos/gradle-command-action@v1.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gradle-version: ${{ steps.gradle.version }}
          arguments: publish
          wrapper-cache-enabled: false
