# This action should be triggered on any PR merge to our main branch
on:
  push:
    branches:
      - main

jobs:
  artifact:
    name: Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ rabbit-hole ]
    steps:
      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get Release Tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.1

      - name: Set Artifact Version
        run: |
          echo Artifact version: ${{ steps.previoustag.outputs.tag }}
          echo "version=${{ steps.previoustag.outputs.tag }}" > gradle.properties

      - name: Gradle Build Artifact
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew ${{ matrix.service }}:build

      - name: Publish Artifact
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew ${{ matrix.service }}:publish
